<a href="https://colab.research.google.com/github/SUBHASH-KANDHWAY/APPLIED-MACNINE-LEARNING-FOR-HEALTHCARE/blob/main/DNA_CLASSIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# To make sure all of the correct libraries are installed, import each module and print the version number

import sys
import numpy
import sklearn
import pandas

print('Python: {}'.format(sys.version))
print('Numpy: {}'.format(numpy.__version__))
print('Sklearn: {}'.format(sklearn.__version__))
print('Pandas: {}'.format(pandas.__version__))

Python: 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Numpy: 1.18.5
Sklearn: 0.22.2.post1
Pandas: 1.1.2


In [27]:
# Import, change module names
import numpy as np
import pandas as pd

# import the uci Molecular Biology (Promoter Gene Sequences) Data Set
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data'
names = ['Class', 'id', 'Sequence']
data = pd.read_csv(url, names = names)

In [28]:
data.head(10)

Class         id                                           Sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...
5     +     MALEFG  \taggggcaaggaggatggaaagaggttgccgtataaagaaactag...
6     +       MALK  \t\tcagggggtggaggatttaagccatctcctgatgacgcatagt...
7     +       RECA  \t\ttttctacaaaacacttgatactgtatgagcatacagtataat...
8     +       RPOB  \t\tcgacttaatatactgcgacaggacgtccgttctgtgtaaatc...
9     +   RRNAB_P1  \tttttaaatttcctcttgtcaggccggaataactccctataatgc...

In [29]:
data.describe()

Class    id                                           Sequence
count    106   106                                                106
unique     2   106                                                106
top        -   915  \tggccaaaaaatatcttgtactatttacaaaacctatggtaactc...
freq      53     1                                                  1

In [30]:
print(data.iloc[0])

Class                                                       +
id                                                        S10
Sequence    \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
Name: 0, dtype: object


In [31]:
print(data.iloc[:5])

  Class         id                                           Sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...


In [32]:
# Building our Dataset by creating a custom Pandas DataFrame
# Each column in a DataFrame is called a Series. Lets start by making a series for each column.

classes = data.loc[:, 'Class']
print(classes[:5])

0    +
1    +
2    +
3    +
4    +
Name: Class, dtype: object


In [33]:
#gentate list of DNA sequence 
sequence=list(data.loc[:,'Sequence'])
dataset={}

#loop through sequence and split into individual nucleotide
for i ,seq in enumerate(sequence):
   nucleotides=list(seq)
   nucleotides=[x for x in nucleotides if x!='\t']
   #append class assignment
   nucleotides.append(classes[i])
   #add to the data set
   dataset[i]=nucleotides
print(dataset[0])

['t', 'a', 'c', 't', 'a', 'g', 'c', 'a', 'a', 't', 'a', 'c', 'g', 'c', 't', 't', 'g', 'c', 'g', 't', 't', 'c', 'g', 'g', 't', 'g', 'g', 't', 't', 'a', 'a', 'g', 't', 'a', 't', 'g', 't', 'a', 't', 'a', 'a', 't', 'g', 'c', 'g', 'c', 'g', 'g', 'g', 'c', 't', 't', 'g', 't', 'c', 'g', 't', '+']


In [34]:
#turning the dataset intp pandas datafrma
dframe=pd.DataFrame(dataset)
print(dframe)

   0   1   2   3   4   5   6   7   8    ... 97  98  99  100 101 102 103 104 105
0    t   t   g   a   t   a   c   t   c  ...   c   t   a   g   c   g   c   c   t
1    a   g   t   a   c   g   a   t   g  ...   g   a   g   a   c   t   g   t   a
2    c   c   a   t   g   g   g   t   a  ...   c   t   a   g   t   a   c   c   a
3    t   t   c   t   a   g   g   c   c  ...   t   g   g   a   c   t   g   g   c
4    a   a   t   g   t   g   g   t   t  ...   a   a   g   g   a   t   a   t   a
5    g   t   a   t   a   c   g   a   t  ...   g   c   g   c   a   c   c   c   t
6    c   c   g   g   a   a   g   c   a  ...   g   c   t   a   t   t   t   c   t
7    a   c   a   a   t   a   t   a   a  ...   a   g   g   t   g   c   a   t   a
8    a   t   g   t   t   g   g   a   t  ...   c   a   t   g   g   a   c   c   a
9    t   g   a   g   a   g   g   a   a  ...   t   a   a   t   c   a   g   a   t
10   a   a   a   t   a   a   a   a   t  ...   t   c   c   c   c   c   a   a   a
11   c   c   c   g   c   g   g   c   a  

In [35]:
df=dframe.transpose()
print(df.iloc[:5])

  0  1  2  3  4  5  6  7  8  9  10 11 12  ... 45 46 47 48 49 50 51 52 53 54 55 56 57
0  t  a  c  t  a  g  c  a  a  t  a  c  g  ...  c  g  g  g  c  t  t  g  t  c  g  t  +
1  t  g  c  t  a  t  c  c  t  g  a  c  a  ...  a  c  g  c  a  t  c  g  c  c  a  a  +
2  g  t  a  c  t  a  g  a  g  a  a  c  t  ...  a  a  c  c  a  c  c  c  g  g  c  g  +
3  a  a  t  t  g  t  g  a  t  g  t  g  t  ...  a  c  t  a  a  c  a  a  a  c  t  c  +
4  t  c  g  a  t  a  a  t  t  a  a  c  t  ...  c  c  t  c  c  g  t  g  g  t  a  g  +

[5 rows x 58 columns]


In [36]:
df.describe()

0    1    2    3    4    5    6   ...   51   52   53   54   55   56   57
count   106  106  106  106  106  106  106  ...  106  106  106  106  106  106  106
unique    4    4    4    4    4    4    4  ...    4    4    4    4    4    4    2
top       t    a    a    c    a    a    a  ...    t    t    c    c    c    t    -
freq     38   34   30   30   36   42   38  ...   33   35   32   29   29   34   53

[4 rows x 58 columns]

In [37]:
df.rename(columns={57:'Class'},inplace=True)
print(df.iloc[:5])

   0  1  2  3  4  5  6  7  8  9 10 11  ... 46 47 48 49 50 51 52 53 54 55 56 Class
0  t  a  c  t  a  g  c  a  a  t  a  c  ...  g  g  g  c  t  t  g  t  c  g  t     +
1  t  g  c  t  a  t  c  c  t  g  a  c  ...  c  g  c  a  t  c  g  c  c  a  a     +
2  g  t  a  c  t  a  g  a  g  a  a  c  ...  a  c  c  a  c  c  c  g  g  c  g     +
3  a  a  t  t  g  t  g  a  t  g  t  g  ...  c  t  a  a  c  a  a  a  c  t  c     +
4  t  c  g  a  t  a  a  t  t  a  a  c  ...  c  t  c  c  g  t  g  g  t  a  g     +

[5 rows x 58 columns]


In [38]:
df.describe()

0    1    2    3    4    5    6  ...   51   52   53   54   55   56 Class
count   106  106  106  106  106  106  106  ...  106  106  106  106  106  106   106
unique    4    4    4    4    4    4    4  ...    4    4    4    4    4    4     2
top       t    a    a    c    a    a    a  ...    t    t    c    c    c    t     -
freq     38   34   30   30   36   42   38  ...   33   35   32   29   29   34    53

[4 rows x 58 columns]

In [39]:
# desribe does not tell us enough information since the attributes are text. Lets record value counts for each sequence
series = []
for name in df.columns:
  series.append(df[name].value_counts())
info=pd.DataFrame(series)
details=info.transpose()
print(details)

      0     1     2     3     4     5  ...    52    53    54    55    56  Class
t  38.0  26.0  27.0  26.0  22.0  24.0  ...  35.0  30.0  23.0  29.0  34.0    NaN
c  27.0  22.0  21.0  30.0  19.0  18.0  ...  21.0  32.0  29.0  29.0  17.0    NaN
a  26.0  34.0  30.0  22.0  36.0  42.0  ...  25.0  22.0  26.0  24.0  27.0    NaN
g  15.0  24.0  28.0  28.0  29.0  22.0  ...  25.0  22.0  28.0  24.0  28.0    NaN
-   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   53.0
+   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   53.0

[6 rows x 58 columns]


In [40]:
# Unfortunately, we can't run machine learning algorithms on the data in 'String' formats. As a result, we need to switch
# it to numerical data. This can easily be accomplished using the pd.get_dummies() function
numerical_df = pd.get_dummies(df)
numerical_df.iloc[:5]

0_a  0_c  0_g  0_t  1_a  1_c  ...  56_a  56_c  56_g  56_t  Class_+  Class_-
0    0    0    0    1    1    0  ...     0     0     0     1        1        0
1    0    0    0    1    0    0  ...     1     0     0     0        1        0
2    0    0    1    0    0    0  ...     0     0     1     0        1        0
3    1    0    0    0    1    0  ...     0     1     0     0        1        0
4    0    0    0    1    0    1  ...     0     0     1     0        1        0

[5 rows x 230 columns]

In [41]:
# We don't need both class columns.  Lets drop one then rename the other to simply 'Class'.
df = numerical_df.drop(columns=['Class_-'])

df.rename(columns = {'Class_+': 'Class'}, inplace = True)
print(df.iloc[:5])

   0_a  0_c  0_g  0_t  1_a  1_c  1_g  ...  55_g  55_t  56_a  56_c  56_g  56_t  Class
0    0    0    0    1    1    0    0  ...     1     0     0     0     0     1      1
1    0    0    0    1    0    0    1  ...     0     0     1     0     0     0      1
2    0    0    1    0    0    0    0  ...     0     0     0     0     1     0      1
3    1    0    0    0    1    0    0  ...     0     1     0     1     0     0      1
4    0    0    0    1    0    1    0  ...     0     0     0     0     1     0      1

[5 rows x 229 columns]


In [42]:
# Use the model_selection module to separate training and testing datasets
from sklearn import model_selection

# Create X and Y datasets for training
X = np.array(df.drop(['Class'], 1))
y = np.array(df['Class'])

# define seed for reproducibility
seed = 1

# split data into training and testing datasets
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25, random_state=seed)

In [43]:
print(X_train, X_test, y_train, y_test)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 1]] [[0 0 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]] [0 0 0 1 1 1 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 1 0 1 1 0
 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 0 1
 0 1 0 1 1] [0 1 0 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0]


In [44]:
# Now that we have our dataset, we can start building algorithms! We'll need to import each algorithm we plan on using
# from sklearn.  We also need to import some performance metrics, such as accuracy_score and classification_report.

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

In [45]:
# define scoring method
scoring = 'accuracy'

# Define models to train
names = ["Nearest Neighbors", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "SVM Linear", "SVM RBF", "SVM Sigmoid"]

classifiers = [
    KNeighborsClassifier(n_neighbors = 3),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    SVC(kernel = 'linear'), 
    SVC(kernel = 'rbf'),
    SVC(kernel = 'sigmoid')
]
models=zip(names,classifiers)
results=[]
names=[]
for name , model in models:
  kfold=model_selection.KFold(n_splits=10, shuffle=True)
  cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
  results.append(cv_results)
  names.append(name)
  msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
  print(msg)
  

Nearest Neighbors: 0.798214 (0.159329)
Gaussian Process: 0.871429 (0.128968)
Decision Tree: 0.760714 (0.116332)
Random Forest: 0.682143 (0.119202)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Neural Net: 0.885714 (0.067857)
AdaBoost: 0.898214 (0.094170)
Naive Bayes: 0.862500 (0.117925)
SVM Linear: 0.873214 (0.096973)
SVM RBF: 0.900000 (0.122474)
SVM Sigmoid: 0.900000 (0.134629)


In [52]:
# Remember, performance on the training data is not that important. We want to know how well our algorithms
# can generalize to new data.  To test this, let's make predictions on the validation dataset.

for name, model in models:
  model.fit(X_train, y_train)
  predictions = model.predict(X_test)
  print(name)
  print(accuracy_score(y_test, predictions))
  print(classification_report(y_test, predictions))
    
# Accuracy - ratio of correctly predicted observation to the total observations. 
# Precision - (false positives) ratio of correctly predicted positive observations to the total predicted positive observations
# Recall (Sensitivity) - (false negatives) ratio of correctly predicted positive observations to the all observations in actual class - yes.
# F1 score - F1 Score is the weighted average of Precision and Recall. Therefore, this score takes both false positives and false 